services:
  bento_db_service:
    image: postgres:17
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - bento_postgres_data:/var/lib/postgresql/data
    networks:
      - bento_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  indexer_service:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      bento_db_service:
        condition: service_healthy
    networks:
      - bento_network
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./src:/app/src

volumes:
  bento_postgres_data:

networks:
  bento_network:
    driver: bridge